### ISSUE TITLE
load issue on lispworks

### ISSUE THREAD

**Issue by hufengtao** [cl-rabbit/cl-amqp#6]
(define-condition amqp-unknown-method-error (amqp-connection-error)
  ((method-signature :initarg :method-signature
                     :reader #:amqp-error-method-signature)))

(define-condition amqp-unknown-method-class-error (amqp-connection-error)
  ((method-class :initarg :method-class
                 :reader :amqp-error-method-class)))
(define-condition amqp-unknown-method-error (amqp-connection-error)
  ((method-signature :initarg :method-signature
                     :reader :amqp-error-method-signature)))

Shoud change to =====>

(define-condition amqp-unknown-method-class-error (amqp-connection-error)
  ((method-class :initarg :method-class
                 :reader #:amqp-error-method-class)))

**Comment by deadtrickster** [comment]
Hi, thanks for the report. Could you please try master now?
